requires "Kossy";
requires "Redis::Fast";
requires 'HTTP::Parser::XS';
requires "Starlet";
requires 'JSON::XS';
requires 'Cache::Memcached::Fast';
requires 'Sereal';
requires 'IO::Compress::Gzip';
requires 'IO::Uncompress::Gunzip';
